#!/bin/bash

ufw --force disable
ufw --force reset

ufw default deny incoming
ufw default deny outgoing
ufw default deny routed
ufw allow 22/tcp
ufw allow out to 147.46.80.1 # 학교 네임서버 1
ufw allow out to 147.46.37.10 # 학교 네임서버 2
ufw allow out to 147.46.78.91 # sherry
ufw allow out to 147.46.78.164 # id 서버
ufw allow out to 34.215.6.16 # pp2018f.snucse.org
ufw allow out to 147.46.219.145 # 컴퓨터 신기술 특강 채점 서버

ufw --force enable
