all:
	true
install:
	mkdir -p $(DESTDIR)/usr/sbin
	cp bacchus-postdist $(DESTDIR)/usr/sbin/
	mkdir -p $(DESTDIR)/usr/lib/systemd/system
	cp bacchus-postdist.service $(DESTDIR)/usr/lib/systemd/system/
