#!/bin/bash

pc=$(/usr/sbin/bacchus-pcdb-lookup)
hostname=$(echo "$pc" | awk '{print $1}')
iface=$(echo "$pc" | awk '{print $4}')

cat > /etc/nsswitch.conf <<EOF
passwd:         compat winbind
group:          compat winbind
shadow:         compat
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
EOF

cat > /etc/samba/smb.conf <<EOF
#======================= Global Settings =======================

[global]

## Browsing/Identification ###

# Change this to the workgroup/NT-domain name your Samba server will part of
   workgroup = CSE

# hostname
   netbios name = $hostname

# server string is the equivalent of the NT Description field
   server string = $hostname

# Windows Internet Name Serving Support Section:
# WINS Support - Tells the NMBD component of Samba to enable its WINS Server
   wins support = yes

# WINS Server - Tells the NMBD components of Samba to be a WINS Client
# Note: Samba can be either a WINS Server, or a WINS Client, but NOT both
# wins domain server : colada
   wins server = 147.46.240.37

# hostname resolving method
   name resolve order = wins host lmhosts bcast

# This will prevent nmbd to search for NetBIOS names through DNS.
   dns proxy = no

#### Networking ####

# The specific set of interfaces / networks to bind to
# This can be either the interface name or an IP address/netmask;
# interface names are normally preferred
   interfaces = $iface

# Only bind to the named interfaces and/or networks; you must use the
# 'interfaces' option above to use this.
# It is recommended that you enable this feature if your Samba machine is
# not protected by a firewall or is a firewall itself.  However, this
# option cannot handle dynamic or non-broadcast interfaces correctly.
   bind interfaces only = yes

# networking layer configuration
   socket options = TCP_NODELAY SO_RCVBUF=8192 SO_SNDBUF=8192

#### Debugging/Accounting ####

# This tells Samba to use a separate log file for each machine
# that connects
   log file = /var/log/samba/log.%m

# Cap the size of the individual log files (in KiB).
   max log size = 1000

# If you want Samba to only log through syslog then set the following
# parameter to 'yes'.
#   syslog only = no

# We want Samba to log a minimum amount of information to syslog. Everything
# should go to /var/log/samba/log.{smbd,nmbd} instead. If you want to log
# through syslog you should set the following parameter to something higher.
   syslog = 0

# Do something sensible when Samba crashes: mail the admin a backtrace
   panic action = /usr/share/samba/panic-action %d


####### Authentication #######

# Server role. Defines in which mode Samba will operate. Possible
# values are "standalone server", "member server", "classic primary
# domain controller", "classic backup domain controller", "active
# directory domain controller".
#
# Most people will want "standalone sever" or "member server".
# Running as "active directory domain controller" will require first
# running "samba-tool domain provision" to wipe databases and create a
# new domain.
   server role = member server
   security = ads

# plugin interface for Winbind to store SID/uid/gid mapping tables
   idmap config * : backend = tdb
   idmap config CSE : backend = rid

# If you are using encrypted passwords, Samba will need to know what
# password database type you are using.
   passdb backend = tdbsam

   obey pam restrictions = yes

# This boolean parameter controls whether Samba attempts to sync the Unix
# password with the SMB password when the encrypted SMB password in the
# passdb is changed.
# SNUCSE users must change their passwords only through the community site
   unix password sync = no

# For Unix password sync to work on a Debian GNU/Linux system, the following
# parameters must be set (thanks to Ian Kahan <<kahan@informatik.tu-muenchen.de> for
# sending the correct chat script for the passwd program in Debian Sarge).
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .

# This boolean controls whether PAM will be used for password changes
# when requested by an SMB client instead of the program listed in
# 'passwd program'. The default is 'no'.
   pam password change = yes

# This option controls how unsuccessful authentication attempts are mapped
# to anonymous connections
   map to guest = bad user

########## Domains ###########

# do not try to become local master
   local master = no

# neither domain master
   domain master = no

# nmbd is not a preferred master browser
   preferred master = no

# do not allow trusted domains; allow CSE only
   allow trusted domains = no

#
# The following settings only takes effect if 'server role = primary
# classic domain controller', 'server role = backup domain controller'
# or 'domain logons' is set
#

# It specifies the location of the user's
# profile directory from the client point of view) The following
# required a [profiles] share to be setup on the samba server (see
# below)
;   logon path = \\%N\profiles\%U
# Another common choice is storing the profile in the user's home directory
# (this is Samba's default)
#   logon path = \\%N\%U\profile

# The following setting only takes effect if 'domain logons' is set
# It specifies the location of a user's home directory (from the client
# point of view)
;   logon drive = H:
#   logon home = \\%N\%U

# The following setting only takes effect if 'domain logons' is set
# It specifies the script to run during logon. The script must be stored
# in the [netlogon] share
# NOTE: Must be store in 'DOS' file format convention
;   logon script = logon.cmd

# This allows Unix users to be created on the domain controller via the SAMR
# RPC pipe.  The example command creates a user account with a disabled Unix
# password; please adapt to your needs
; add user script = /usr/sbin/adduser --quiet --disabled-password --gecos "" %u

# This allows machine accounts to be created on the domain controller via the
# SAMR RPC pipe.
# The following assumes a "machines" group exists on the system
; add machine script  = /usr/sbin/useradd -g machines -c "%u machine account" -d /var/lib/samba -s /bin/false %u

# This allows Unix groups to be created on the domain controller via the SAMR
# RPC pipe.
; add group script = /usr/sbin/addgroup --force-badname %g

######### Encryption #########
# negotiate with other computers using encrypted passwords
   encrypt passwords = yes

###### SNUCSE Accounts #######
# kerberos realm to use
   realm = snucse.org

# separate Domain and username with +
# WARNING: the character + is used as a special character for NIS in /etc/group
   winbind separator = +

# UNIX unique IDs for Winbind
# two ranges SHOULD NOT overlap
   idmap config * : range = 3000-10000
   idmap config CSE : range = 100000-1000000

# the number of seconds the winbindd daemon will cache user and group information
# before querying a Windows NT server again
   winbind cache time = 15

# always maintain full list of users
   winbind enum users = yes

# as well as groups
   winbind enum groups = yes

# default shell
   template shell = /bin/bash

# default home directory
   template homedir = /csehome/%U

# users without a domain component are treated as is part of domain CSE
   winbind use default domain = yes

# let Samba to determine the best DC to contact dynamically for password query
# colada or newpina
# password server = colada
   password server = *

############ Misc ############

# Using the following line enables you to customise your configuration
# on a per machine basis. The %m gets replaced with the netbios name
# of the machine that is connecting
;   include = /home/samba/etc/smb.conf.%m

# Setup usershare options to enable non-root users to share folders
# with the net usershare command.

# Maximum number of usershare. 0 (default) means that usershare is disabled.
;   usershare max shares = 100

# Allow users who've been granted usershare privileges to create
# public shares, not just authenticated ones
   usershare allow guests = no

# no CUPS device available
   printcap name = /dev/null

# do not load printers for browsing
   load printers = no

# interprete printer information in bsd style
   printing = bsd

######### Name Mangling #########
# new filenames are created with the case that the client passes
   preserve case = yes

# however the default mapping is lower
   default case = lower

# file names are not case sensitive
   case sensitive = no
EOF
