#!/bin/bash

pc=$(/usr/sbin/bacchus-pcdb-lookup)
hostname=$(echo "$pc" | awk '{print $1}')
iface=$(echo "$pc" | awk '{print $4}')

cat > /etc/nsswitch.conf << EOF
passwd:         compat ldap
group:          compat ldap
shadow:         compat
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
EOF

cat > /etc/ldap.conf << EOF

EOF
