#!/bin/bash

set -e

systemctl enable gdm.service
systemctl disable NetworkManager.service

cd /usr/share/gnome-shell
[[ -f gnome-shell-theme.gresource ]] && mv -f gnome-shell-theme.gresource gnome-shell-theme.gresource~
ln -sf /usr/share/themes/Adapta/gnome-shell/gnome-shell-theme.gresource

rm -f /etc/fonts/conf.d/56-emojione-color.conf
dconf update

exit 0
