#!/bin/bash

systemctl enable bacchus-sync-cleanup-all.service sherry.mount

cd /usr/share/xsessions
find . -type f -name "*.desktop" -print0 | xargs -0 -L1 -I{} -- mv "{}" "{}.old"
mv snucse-lab.desktop.old snucse-lab.desktop

mkdir -p /sherry
sudo chown root:root /sherry
sudo chmod 711 /sherry

systemctl start sherry.mount

mkdir -p /sherry/.sync-status
sudo chown root:root /sherry/.sync-status
sudo chmod 711 /sherry/.sync-status

sudo touch /sherry/.guests

sudo mkdir -p /csehome
sudo chown root:root /csehome
sudo chmod 711 /csehome

sudo mkdir -p /csehome/.sync-status
sudo chown root:root /csehome/.sync-status
sudo chmod 711 /csehome/.sync-status

cd /etc/gdm3
mv -f PostLogin/Default PostLogin/Default.old
mv -f PostSession/Default PostSession/Default.old

cat >> PostLogin/Default <<EOF
#!/bin/bash
[[ -x /etc/gdm3/PostLogin/Default.bacchus-sync.sh ]] && exec /etc/gdm3/PostLogin/Default.bacchus-sync.sh
exit 0
EOF

cat >> PostSession/Default <<EOF
#!/bin/bash
[[ -x /etc/gdm3/PostSession/Default.bacchus-sync.sh ]] && exec /etc/gdm3/PostSession/Default.bacchus-sync.sh
exit 0
EOF

chmod +x PostLogin/Default PostSession/Default

exit 0
