#!/bin/bash

set -e

oldhostname=$(hostname)
pc=$(/usr/sbin/bacchus-pcdb-lookup)
hostname=$(echo "$pc" | awk '{print $1}')
ip=$(echo "$pc" | awk '{print $2}')
gateway=$(echo "$ip" | awk -F"." '{print $1"."$2"."$3".1"}')
iface=$(echo "$pc" | awk '{print $5}')

cat > /etc/netplan/50-cloud-init.yaml <<EOF
network:
    ethernets:
        $iface:
            addresses:
                - $ip/24
            gateway4: $gateway
            nameservers:
                addresses: [147.46.80.1, 147.46.37.10]
                search: []
            optional: true
    version: 2
EOF

hostnamectl set-hostname "$hostname"
hosts=$(grep -v "$oldhostname" /etc/hosts)
echo "$hosts" > /etc/hosts
cat >> /etc/hosts <<EOF
127.0.0.1 $hostname
EOF

echo "$pc"

#isystemctl restart networking
netplan generate
netplan apply
exit 0
