#!/bin/bash

set -e

oldhostname=$(hostname)
pc=$(/usr/sbin/bacchus-pcdb-lookup)
hostname=$(echo "$pc" | awk '{print $1}')
ip=$(echo "$pc" | awk '{print $2}')
gateway=$(echo "$ip" | awk -F"." '{print $1"."$2"."$3".1"}')
iface=$(echo "$pc" | awk '{print $5}')

cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

auto $iface
iface $iface inet static
  address $ip
  netmask 24
  gateway $gateway
  dns-nameservers 147.46.80.1 147.46.37.10
EOF

hostnamectl set-hostname "$hostname"
hosts=$(grep -v "$oldhostname" /etc/hosts)
echo "$hosts" > /etc/hosts
cat >> /etc/hosts <<EOF
127.0.0.1 $hostname
EOF

echo "$pc"
systemctl restart networking

exit 0
